version: '3.8'

services:
  dashboard:
    build: .
    container_name: eric_dashboard_dev
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://data_manager_eric_user:dTlysQDHoqHMI3zDL4MovqB4QdKQpB1C@dpg-d9hdvsjeo5us73e18fi0-a.ohio-postgres.render.com/data_manager_eric
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
